from collections import namedtuple





snapshots_list = [
    {
        "__search_key__": "prod/snapshot?project=BIMINI&code=43095020BIMINI",
        "_skip_files": False,
        "asset_code": None,
        "asset_description": None,
        "asset_id": None,
        "asset_library": None,
        "asset_name": None,
        "asset_uuid": None,
        "code": "43095020BIMINI",
        "container_type": 2,
        "context": "plate/sv4ks100/exr",
        "context_type": "exr",
        "create_location": "portland",
        "department": "plate",
        "description": "n/a",
        "file_name": None,
        "generation": None,
        "generation_current": None,
        "id": 43095020,
        "instance_code": None,
        "instance_id": None,
        "instance_name": None,
        "instance_uuid": None,
        "is_current": False,
        "is_latest": True,
        "level": "RD1212",
        "level_container_type": 2,
        "level_id": 40009014,
        "level_type": "prod/shot?project=BIMINI",
        "login": "rvigorito",
        "metadata": {
            "category": "bg01",
            "descriptor": "dn_rt",
            "farm0_lss": "packet_ttruscott_submission_2024-06-06.07:31:%02d.yml",
            "farm1_lss": "ga1500_bg01_dn_rt_v%03d.nk",
            "farm2_lss": "payload.20240606_073243_%06d.py",
            "in": 1001,
            "main_lens": "ddhb_ga1500bg01",
            "main_lss": "ga1500_bg01_dn_rt_v001.%04d.exr",
            "orig_in": 1001,
            "orig_out": 1209,
            "out": 1180,
            "proxy_lss": "ga1500_bg01_dn_rt_v001.%04d.exr",
            "source_path": "/dd/shows/BIMINI/GA/1500/SHARED/IMG/plate/ga1500_bg01_dn_v001.sv4ks100/ga1500_bg01_dn_v001.%04d.exr",
        },
        "name": "rd1212_bg01_dn_rt",
        "parent": None,
        "plate_code": None,
        "plate_id": None,
        "plate_name": None,
        "plate_uuid": None,
        "project": "BIMINI",
        "publish_timestamp": "2024-08-01 16:21:53.753238",
        "registration_complete": False,
        "relative_dir": None,
        "render_code": "41042793BIMINI",
        "render_id": 41042793,
        "render_name": "rd1212_bg01_dn_rt",
        "s_status": None,
        "seal": False,
        "search_id": 41042793,
        "search_type": "prod/render?project=BIMINI",
        "snapshot": "<snapshot/>",
        "snapshot_files": None,
        "snapshot_type": "work_plate",
        "subcontext": "sv4ks100",
        "version": 1,
        "was_current": False,
        "was_current_at": None,
    },
    {
        "__search_key__": "prod/snapshot?project=BIMINI&code=43094217BIMINI",
        "_skip_files": False,
        "asset_code": None,
        "asset_description": None,
        "asset_id": None,
        "asset_library": None,
        "asset_name": None,
        "asset_uuid": None,
        "code": "43094217BIMINI",
        "container_type": 2,
        "context": "plate/sv4ks100/exr",
        "context_type": "exr",
        "create_location": "portland",
        "department": "plate",
        "description": "n/a",
        "file_name": None,
        "generation": None,
        "generation_current": None,
        "id": 43094217,
        "instance_code": None,
        "instance_id": None,
        "instance_name": None,
        "instance_uuid": None,
        "is_current": True,
        "is_latest": True,
        "level": "RD1212",
        "level_container_type": 2,
        "level_id": 40009014,
        "level_type": "prod/shot?project=BIMINI",
        "login": "rvigorito",
        "metadata": {
            "category": "bg01",
            "farm_lss": "payload.20240527_161902_%06d.py",
            "in": 1001,
            "main_lss": "ga1500_bg01_v001.%04d.exr",
            "orig_in": 1001,
            "orig_out": 1209,
            "out": 1209,
            "proxy_lss": "ga1500_bg01_v001.%04d.exr",
            "source_path": "/dd/shows/BIMINI/SHARED/IMG/scan/20240523/_DLL17375_BIMINI_240522_SO034_DDO_4k_scan_ref_v2/BIMINI_240522_SO034_DDO_4k_scan_ref_v2/exr/078_GA_1500/4312x2274/078_GA_1500.%04d.exr",
        },
        "name": "rd1212_bg01",
        "parent": None,
        "plate_code": None,
        "plate_id": None,
        "plate_name": None,
        "plate_uuid": None,
        "project": "BIMINI",
        "publish_timestamp": "2024-08-01 15:27:32.175851",
        "registration_complete": True,
        "relative_dir": None,
        "render_code": "41042490BIMINI",
        "render_id": 41042490,
        "render_name": "rd1212_bg01",
        "s_status": None,
        "seal": True,
        "search_id": 41042490,
        "search_type": "prod/render?project=BIMINI",
        "snapshot": "<snapshot/>",
        "snapshot_files": None,
        "snapshot_type": "work_plate",
        "subcontext": "sv4ks100",
        "version": 1,
        "was_current": True,
        "was_current_at": "2024-08-01 16:09:36.989852",
    },
    {
        "__search_key__": "prod/snapshot?project=BIMINI&code=43095016BIMINI",
        "_skip_files": False,
        "asset_code": None,
        "asset_description": None,
        "asset_id": None,
        "asset_library": None,
        "asset_name": None,
        "asset_uuid": None,
        "code": "43095016BIMINI",
        "container_type": 2,
        "context": "plate/sv4ks100/exr",
        "context_type": "exr",
        "create_location": "portland",
        "department": "plate",
        "description": "n/a",
        "file_name": None,
        "generation": None,
        "generation_current": None,
        "id": 43095016,
        "instance_code": None,
        "instance_id": None,
        "instance_name": None,
        "instance_uuid": None,
        "is_current": False,
        "is_latest": True,
        "level": "RD1212",
        "level_container_type": 2,
        "level_id": 40009014,
        "level_type": "prod/shot?project=BIMINI",
        "login": "rvigorito",
        "metadata": {
            "category": "bg01",
            "descriptor": "dn",
            "farm0_lss": "packet_ttruscott_submission_2024-06-05.17:55:%02d.yml",
            "farm1_lss": "bimini_denoise_to1_v%03d.nk",
            "farm2_lss": "payload.20240605_175618_%06d.py",
            "farm3_lss": "bimini_denoise_to1_v%03d.nk_uTZIfa.yard",
            "in": 1001,
            "main_lss": "ga1500_bg01_dn_v001.%04d.exr",
            "orig_in": 1001,
            "orig_out": 1209,
            "out": 1209,
            "proxy_lss": "ga1500_bg01_dn_v001.%04d.exr",
            "source_path": "/dd/shows/BIMINI/GA/1500/SHARED/IMG/plate/ga1500_bg01_v001.sv4ks100/ga1500_bg01_v001.%04d.exr",
        },
        "name": "rd1212_bg01_dn",
        "parent": None,
        "plate_code": None,
        "plate_id": None,
        "plate_name": None,
        "plate_uuid": None,
        "project": "BIMINI",
        "publish_timestamp": "2024-08-01 16:21:31.144589",
        "registration_complete": False,
        "relative_dir": None,
        "render_code": "41042790BIMINI",
        "render_id": 41042790,
        "render_name": "rd1212_bg01_dn",
        "s_status": None,
        "seal": False,
        "search_id": 41042790,
        "search_type": "prod/render?project=BIMINI",
        "snapshot": "<snapshot/>",
        "snapshot_files": None,
        "snapshot_type": "work_plate",
        "subcontext": "sv4ks100",
        "version": 1,
        "was_current": False,
        "was_current_at": None,
    },
    {
        "__search_key__": "prod/snapshot?project=BIMINI&code=43095027BIMINI",
        "_skip_files": False,
        "asset_code": None,
        "asset_description": None,
        "asset_id": None,
        "asset_library": None,
        "asset_name": None,
        "asset_uuid": None,
        "code": "43095027BIMINI",
        "container_type": 2,
        "context": "plate/sv4ks100/exr",
        "context_type": "exr",
        "create_location": "portland",
        "department": "plate",
        "description": "n/a",
        "file_name": None,
        "generation": None,
        "generation_current": None,
        "id": 43095027,
        "instance_code": None,
        "instance_id": None,
        "instance_name": None,
        "instance_uuid": None,
        "is_current": False,
        "is_latest": True,
        "level": "RD1212",
        "level_container_type": 2,
        "level_id": 40009014,
        "level_type": "prod/shot?project=BIMINI",
        "login": "rvigorito",
        "metadata": {
            "category": "el01",
            "farm_lss": "payload.20240528_153035_%06d.py",
            "in": 1001,
            "main_lss": "ga1500_el01_v001.%04d.exr",
            "orig_in": 1001,
            "orig_out": 1361,
            "out": 1361,
            "proxy_lss": "ga1500_el01_v001.%04d.exr",
            "source_path": "/dd/shows/BIMINI/SHARED/IMG/scan/20240523/_DLL17375_BIMINI_240522_SO034_DDO_4k_scan_ref_v2/BIMINI_240522_SO034_DDO_4k_scan_ref_v2/exr/078_GA_1500_EL01/4312x2274/078_GA_1500_EL01.%04d.exr",
        },
        "name": "rd1212_el01",
        "parent": None,
        "plate_code": None,
        "plate_id": None,
        "plate_name": None,
        "plate_uuid": None,
        "project": "BIMINI",
        "publish_timestamp": "2024-08-01 16:23:43.699588",
        "registration_complete": False,
        "relative_dir": None,
        "render_code": "41042808BIMINI",
        "render_id": 41042808,
        "render_name": "rd1212_el01",
        "s_status": None,
        "seal": False,
        "search_id": 41042808,
        "search_type": "prod/render?project=BIMINI",
        "snapshot": "<snapshot/>",
        "snapshot_files": None,
        "snapshot_type": "work_plate",
        "subcontext": "sv4ks100",
        "version": 1,
        "was_current": False,
        "was_current_at": None,
    },
]



Snapshot = namedtuple(
    "Snapshot",
    [key for key in snapshots_list[0].keys() if not str(key).startswith("_")],
)

snapshots = []

for snapshot in snapshots_list:
    # Remove the keys that are not included in the namedtuple
    snapshot = {key: value for key, value in snapshot.items() if key in Snapshot._fields}
    snapshots.append(Snapshot(**snapshot))